### ISSUE TITLE
Error on Safari due to JSON-LD structure in page header

### ISSUE THREAD

**Issue by greg-bookyrslf** [sharetribe/web-template#416]
The JSON-LD script tag injected into the page head at  [Page.js](https://github.com/sharetribe/web-template/blob/7813c524cf9b91fb5f9da5cb536cf77ae0c32750/src/components/Page/Page.js#L200) creates a JSON object like:
```json
[
   {
      "@context":"http://schema.org",
      "@type":"WebPage",
      "description":"marketplace",
      "name":"marketplace",
      "image":[
         "https://sharetribe-assets.imgix.net/65fb4409-655d-45af-8836-b7c596316f62/raw/db/f5d3ed6a44c89c6ccc440e11a273d108f98eac?auto=format&fit=clip&h=1200&w=1200&s=dea58b02f96c1ab06541e8c9b97e0779"
      ]
   },
   {
      "@context":"http://schema.org",
      "@type":"Organization",
      "@id":"https://marketplace.com#organization",
      "url":"https://marketplace.com",
      "name":"marketplace",
      "sameAs":[
         
      ]
   },
   {
      "@context":"http://schema.org",
      "@type":"WebSite",
      "url":"https://marketplace.com",
      "description":"An online marketplace.",
      "name":"marketplace"
   }
]
```

The fact it is an outer Array generates an error on Safari browser. The error is `undefined is not an object (evaluating 'r["@context"].toLowerCase')`

There is no error in other browsers. 

See this [stack overflow](https://stackoverflow.com/questions/76995140/safari-throws-when-parsing-json-ld) answer for a possible fix.

**Comment by Gnito** [comment]
Thanks for reporting!

This is not a serious issue - and in fact it looks like to be a bug on Safari, since it doesn't accept an array as valid JSON-LD. The data is used by Search engine bots and they recognize this as valid JSON-LD. Therefore, the main problem is that this might cause noise on Safari's debugging tools.

That being said, changing the structured data to use the suggested "@graph" seems to be OK (to my understanding). I'll write a PR.
